# romcat config
# Edit "folder" to point at your real ROM directories.
# Edit "command" to whatever launches that ROM on your machine.
# {rom} is replaced with the full path to the ROM file (already quoted).

systems:
  nes:
    name: "NES"
    folder: "/home/jmc/Storage/disk3tb/ROMS/NES ROMS USA/"
    extensions: [".nes"]
    command: "flatpak run ca._0ldsk00l.Nestopia {rom}"

  snes:
    name: "SNES"
    folder: "/home/jmc/Storage/disk3tb/ROMS/SNES Roms/"
    extensions: [".sfc", ".smc"]
    command: "flatpak run com.snes9x.Snes9x {rom}"

  n64:
    name: "N64"
    folder: "/home/jmc/Storage/disk3tb/ROMS/Nintendo 64 Roms/"
    extensions: [".n64", ".z64", ".v64"]
    command: "flatpak run io.github.gopher64.gopher64 {rom}"

  Gamecube:
    name: "Gamecube"
    folder: "/home/jmc/Storage/disk3tb/ROMS/Gamecube/"
    extensions: [".iso", ".gcm", ".gcz", ".rvz", ".wbfs", ".wia", ".ciso", ".tgc", ".nfs", ".dol", ".elf"]
    command: "flatpak run org.DolphinEmu.dolphin-emu {rom}"

  WiiU:
    name: "WiiU"
    folder:
    - "/home/jmc/Storage/nvme2tb/WiiU Roms/"
    - "/home/jmc/Storage/disk3tb/ROMS/WiiU Roms/"
    extensions: [".rpx", ".wud", ".wux", ".wua"]
    command: "flatpak run info.cemu.Cemu -g {rom}"

  Switch:
    name: "Switch"
    folder: "/home/jmc/Storage/nvme2tb/Switch Games/"
    extensions: [".nsp", ".xci"]
    command: "env DISPLAY=:0 WAYLAND_DISPLAY=wayland-0 /home/jmc/Applications/Eden -g {rom}"

# Get a free key at https://www.steamgriddb.com/profile/preferences/api
steamgriddb:
  api_key: "757ea72927d3d239eb601cc2f30bbb9d"

# io.github.xyproto.zsnes
# dev.bsnes.bsnes
